services:
  postgres:
    image: postgres:16-alpine
    container_name: auss_postgres
    environment:
      POSTGRES_USER: auss_user
      POSTGRES_PASSWORD: auss_password
      POSTGRES_DB: auss_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U auss_user" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local
